// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pb/replication.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Op            uint32                 `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_pb_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_pb_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_pb_replication_proto_rawDescGZIP(), []int{0}
}

func (x *Mutation) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Mutation) GetOp() uint32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *Mutation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Mutation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pb_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pb_replication_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_pb_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_pb_replication_proto_rawDescGZIP(), []int{2}
}

var File_pb_replication_proto protoreflect.FileDescriptor

const file_pb_replication_proto_rawDesc = "" +
	"\n" +
	"\x14pb/replication.proto\x12\vreplication\"T\n" +
	"\bMutation\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\rR\x02op\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x11\n" +
	"\x0fSnapshotRequest2\x8d\x01\n" +
	"\vreplication\x128\n" +
	"\rApplyMutation\x12\x15.replication.Mutation\x1a\x10.replication.Ack\x12D\n" +
	"\vGetSnapshot\x12\x1c.replication.SnapshotRequest\x1a\x15.replication.Mutation0\x01B\x05Z\x03/pbb\x06proto3"

var (
	file_pb_replication_proto_rawDescOnce sync.Once
	file_pb_replication_proto_rawDescData []byte
)

func file_pb_replication_proto_rawDescGZIP() []byte {
	file_pb_replication_proto_rawDescOnce.Do(func() {
		file_pb_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_replication_proto_rawDesc), len(file_pb_replication_proto_rawDesc)))
	})
	return file_pb_replication_proto_rawDescData
}

var file_pb_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_replication_proto_goTypes = []any{
	(*Mutation)(nil),        // 0: replication.Mutation
	(*Ack)(nil),             // 1: replication.Ack
	(*SnapshotRequest)(nil), // 2: replication.SnapshotRequest
}
var file_pb_replication_proto_depIdxs = []int32{
	0, // 0: replication.replication.ApplyMutation:input_type -> replication.Mutation
	2, // 1: replication.replication.GetSnapshot:input_type -> replication.SnapshotRequest
	1, // 2: replication.replication.ApplyMutation:output_type -> replication.Ack
	0, // 3: replication.replication.GetSnapshot:output_type -> replication.Mutation
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_replication_proto_init() }
func file_pb_replication_proto_init() {
	if File_pb_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_replication_proto_rawDesc), len(file_pb_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_replication_proto_goTypes,
		DependencyIndexes: file_pb_replication_proto_depIdxs,
		MessageInfos:      file_pb_replication_proto_msgTypes,
	}.Build()
	File_pb_replication_proto = out.File
	file_pb_replication_proto_goTypes = nil
	file_pb_replication_proto_depIdxs = nil
}
